// Banco editorial de compuestos grecolatinos. Se mantiene separado de la interfaz
// para ampliar o revisar el corpus sin tocar la lógica del juego.
window.createWordBank = (excludedWords = []) => {
  const roots = [
    ["aero","aero","aire","ἀήρ","el aire"],["agro","agro","campo","ἀγρός","el campo"],["antropo","antropo","ser humano","ἄνθρωπος","el ser humano"],["arqui","arqui","origen, principio","ἀρχή","el origen"],["astro","astro","estrella","ἄστρον","los astros"],["auto","auto","uno mismo","αὐτός","uno mismo"],["biblio","biblio","libro","βιβλίον","los libros"],["bio","bio","vida","βίος","la vida"],["cardio","cardio","corazón","καρδία","el corazón"],["cito","cito","célula","κύτος","las células"],["crono","crono","tiempo","χρόνος","el tiempo"],["demo","demo","pueblo","δῆμος","el pueblo"],["dermo","dermo","piel","δέρμα","la piel"],["eco","eco","casa, entorno","οἶκος","el entorno"],["electro","electro","ámbar","ἤλεκτρον","la electricidad"],["endo","endo","dentro","ἔνδον","el interior"],["entomo","entomo","insecto","ἔντομον","los insectos"],["etno","etno","pueblo, grupo","ἔθνος","los pueblos"],["foto","foto","luz","φῶς","la luz"],["fono","fono","sonido, voz","φωνή","el sonido"],["fito","fito","planta","φυτόν","las plantas"],["gastro","gastro","estómago","γαστήρ","el estómago"],["geo","geo","tierra","γῆ","la Tierra"],["geronto","geronto","anciano","γέρων","la vejez"],["gineco","gineco","mujer","γυνή","la mujer"],["helio","helio","sol","ἥλιος","el Sol"],["hemo","hemo","sangre","αἷμα","la sangre"],["hepato","hepato","hígado","ἧπαρ","el hígado"],["hetero","hetero","diferente","ἕτερος","lo diferente"],["hidro","hidro","agua","ὕδωρ","el agua"],["ictio","ictio","pez","ἰχθύς","los peces"],["icono","icono","imagen","εἰκών","las imágenes"],["lexico","lexico","palabra","λέξις","las palabras"],["lito","lito","piedra","λίθος","las piedras"],["macro","macro","grande","μακρός","lo grande"],["micro","micro","pequeño","μικρός","lo pequeño"],["mito","mito","relato tradicional","μῦθος","los relatos tradicionales"],["morfo","morfo","forma","μορφή","las formas"],["nano","nano","muy pequeño","νᾶνος","lo diminuto"],["neuro","neuro","nervio","νεῦρον","el sistema nervioso"],["odonto","odonto","diente","ὀδούς","los dientes"],["onco","onco","masa, tumor","ὄγκος","los tumores"],["ornito","ornito","ave","ὄρνις","las aves"],["orto","orto","recto, correcto","ὀρθός","lo correcto"],["osteo","osteo","hueso","ὀστέον","los huesos"],["paleo","paleo","antiguo","παλαιός","lo antiguo"],["pato","pato","dolor, enfermedad","πάθος","la enfermedad"],["psico","psico","mente, alma","ψυχή","la mente"],["socio","socio","compañero","socius","la sociedad","latín"],["tele","tele","lejos, a distancia","τῆλε","la distancia"],["termo","termo","calor","θέρμη","el calor"],["topo","topo","lugar","τόπος","los lugares"],["toxico","toxico","veneno","τοξικόν","los venenos"],["zoo","zoo","animal","ζῷον","los animales"]
  ];
  const endings = [
    ["logía","logía","estudio, tratado","λογία",(subject) => `Estudio de ${subject}.`],["grafía","grafía","escritura, representación","γραφία",(subject) => `Representación o descripción de ${subject}.`],["metría","metría","medida","μετρία",(subject) => `Medición relacionada con ${subject}.`],["fobia","fobia","miedo, aversión","φοβία",(subject) => `Miedo o aversión relacionado con ${subject}.`],["filia","filia","afinidad, amor","φιλία",(subject) => `Afinidad o interés por ${subject}.`],["terapia","terapia","tratamiento","θεραπεία",(subject) => `Tratamiento relacionado con ${subject}.`],["patía","patía","afección, padecimiento","πάθεια",(subject) => `Afección relacionada con ${subject}.`],["nomía","nomía","norma, orden","νομία",(subject) => `Conocimiento o sistema aplicado a ${subject}.`]
  ];
  const heritageTerms = [
    ["álgebra","Rama de las matemáticas que opera con símbolos y cantidades.","al","el","árabe","ال"],["alcohol","Sustancia obtenida por fermentación o destilación.","kuḥl","polvo fino","árabe","كحل"],["aceite","Grasa líquida, especialmente la extraída de frutos y semillas.","az-zayt","aceite de oliva","árabe","الزيت"],["azúcar","Sustancia dulce soluble en agua.","as-sukkar","sustancia dulce cristalina","árabe","السكر"],["almohada","Pieza blanda para apoyar la cabeza al dormir.","al-mukhadda","mejilla","árabe","المخدة"],["alcalde","Persona que preside un ayuntamiento.","al-qāḍī","juez","árabe","القاضي"],["ojalá","Expresión de deseo.","in šā’ Allāh","si Dios quiere","árabe","إن شاء الله"],
    ["guerra","Lucha armada entre grupos organizados.","werra","pelea, confusión","germánico","*werra"],["yelmo","Armadura que protegía la cabeza.","helm","protección, casco","germánico","*helmaz"],["jardín","Terreno donde se cultivan plantas ornamentales.","jardin","huerto cercado","francés","jardin"],["garaje","Lugar destinado a guardar vehículos.","garage","guardar","francés","garage"],["hotel","Establecimiento que ofrece alojamiento.","hôtel","casa de huéspedes","francés","hôtel"],["bufé","Comida servida para que cada persona se sirva.","buffet","aparador","francés","buffet"],["maquillaje","Cosmético aplicado al rostro.","maquillage","arreglo del rostro","francés","maquillage"],
    ["tomate","Fruto rojo y jugoso usado como alimento.","tomatl","fruto hinchado","náhuatl","tomatl"],["chocolate","Alimento elaborado con cacao.","xocolātl","bebida amarga","náhuatl","xocolātl"],["aguacate","Fruto verde de pulpa cremosa.","āhuacatl","testículo","náhuatl","āhuacatl"],["coyote","Mamífero canino de América.","coyōtl","can silvestre americano","náhuatl","coyōtl"],["chile","Fruto picante de varias especies de pimiento.","chīlli","pimiento picante","náhuatl","chīlli"],
    ["papa","Tubérculo comestible de la patata.","papa","tubérculo","quechua","papa"],["puma","Felino americano de gran tamaño.","puma","felino de montaña","quechua","puma"],["cóndor","Ave rapaz andina de gran envergadura.","kuntur","gran ave andina","quechua","kuntur"],["cancha","Terreno preparado para practicar un deporte.","kancha","recinto cercado","quechua","kancha"],["carpa","Tienda desmontable de lona.","karpa","cobertura","quechua","karpa"],
    ["hamaca","Red o lona suspendida para descansar.","hamaca","red para dormir","taíno","hamaca"],["canoa","Embarcación ligera y estrecha.","kanoa","embarcación ligera","taíno","kanoa"],["huracán","Viento de fuerza extraordinaria.","hurakán","espíritu de la tormenta","taíno","hurakán"],["barbacoa","Parrilla para asar alimentos.","barbacoa","armazón de palos","taíno","barbacoa"],
    ["izquierda","Lado opuesto a la derecha.","ezker","lado opuesto a la derecha","euskera","ezker"],["pizarra","Roca laminada usada para escribir.","pizarra","piedra plana","euskera","pizarra"],
    ["fútbol","Deporte jugado principalmente con los pies.","football","balón de pie","inglés","football"],["mitin","Reunión pública de carácter político.","meeting","reunión","inglés","meeting"],["suéter","Prenda de punto para cubrir el torso.","sweater","prenda para sudar","inglés","sweater"]
  ];
  const rootMeanings = roots.map(([, , meaning]) => meaning);
  const endingMeanings = endings.map(([, , meaning]) => meaning);
  const optionsFor = (meaning, pool, offset) => [meaning, ...pool.filter((item) => item !== meaning).slice(offset % (pool.length - 3), (offset % (pool.length - 3)) + 3)];
  const excluded = new Set(excludedWords);
  const heritageMeanings = heritageTerms.map(([, , , meaning]) => meaning);
  const heritageChallenges = heritageTerms.map(([word, definition, text, meaning, origin, original], index) => ({
    word, definition, parts: [{ text, meaning, origin, original, options: optionsFor(meaning, heritageMeanings, index) }]
  }));
  const compoundChallenges = roots.flatMap(([form, text, meaning, original, subject, origin = "griego"], rootIndex) => endings.map(([endingForm, endingText, endingMeaning, endingOriginal, definitionFor], endingIndex) => ({
    word: `${form}${endingForm}`,
    definition: definitionFor(subject),
    parts: [
      { text, meaning, origin, original, options: optionsFor(meaning, rootMeanings, rootIndex + endingIndex) },
      { text: endingText, meaning: endingMeaning, origin: "griego", original: endingOriginal, options: optionsFor(endingMeaning, endingMeanings, rootIndex * 2 + endingIndex) }
    ]
  }))).filter(({ word }) => !excluded.has(word));
  return [...heritageChallenges, ...compoundChallenges].slice(0, 396);
};
